import type { Metadata } from "next";
import "./globals.css";
import '../styles/home.css';

export const metadata: Metadata = {
  title: "Next Tour | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html native-dark-active="">
      <body className="max-w-[1800px] mx-auto">
        {children}
      </body>
    </html>
  );
}
